### PR TITLE
Don't use Trivy auth helpers when using Azure

### PR DESCRIPTION
**Pull request by asankov**
and user has provider username and pass in pull secret

### CODE REVIEW

**Comment by patrickpichler** [comment]
By looking at the code, I guess this issue is not just ACR specific, you have the same thing with GCR/ECR. 
https://github.com/aquasecurity/trivy/blob/main/pkg/fanal/image/registry/google/google.go#L37

You mentioned in your discord message, that in order to use azure workload identity, we need to specify a special label on the scanner pod. In my opinion the better fix would be to extend kvisor-controller to make the scanner labels configurable.

**Comment by asankov** [comment]
@patrickpichler 

> By looking at the code, I guess this issue is not just ACR specific, you have the same thing with GCR/ECR.

For GCP - probably yes, need to investigate. For sure, we cannot use username/pass there, but maybe workload identity works out of the box for GCP.
For AWS - no. We have the [workload ID setup for AWS](https://docs.cast.ai/docs/image-scanning#amazon-elastic-container-registry-amazon-ecr). AFAIK AWS does not support username/pass at all, so this is a non-issue for AWS.

**Comment by patrickpichler** [comment]
What you can do in AWS ECR is to use a login password (see [here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/registry_auth.html)), but iMHO we should discourage this. One thing we should be thinking about is, if we want to support cases where you haven an EKS cluster and e.g. pull images from GCR, as in such cases you can not use any of the workload identity solutions (I guess in theory you can setup OIDC to assume identities in other cloud providers via the identity from your kubernetes cluster, but I have no idea if this is actually supported 😅).

**Comment by asankov** [comment]
Closing this, because we opted to go the Workload ID way, and these changes are not needed for now 

See https://github.com/castai/kvisor/pull/265

**Pull request closed without merging**
